version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: omr
      POSTGRES_USER: omr
      POSTGRES_PASSWORD: omr
    volumes:
      - dbdata:/var/lib/postgresql/data
  backend:
    build: ./backend
    command: gunicorn omr_backend.wsgi:application --bind 0.0.0.0:8000
    environment:
      DATABASE_URL: postgres://omr:omr@db:5432/omr
      DJANGO_SECRET_KEY: change-me
      DJANGO_DEBUG: '1'
      ALLOWED_HOSTS: '*'
    volumes:
      - ./backend:/app
    depends_on:
      - db
  frontend:
    build: ./frontend
    environment:
      NEXT_PUBLIC_API_BASE: http://localhost/api
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
  nginx:
    image: nginx:1.27
    volumes:
      - ./deploy/nginx.conf:/etc/nginx/nginx.conf
      - ./backend/media:/media
    ports:
      - '80:80'
    depends_on:
      - frontend
      - backend
volumes:
  dbdata:
